---
abstract: 'Catalan < > Spanish machine translation [ OBSOLETE - Use WWW::Translate::Apertium instead ]'
author:
  - 'Enrique Nell <blas.gordon@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Translate-interNOSTRUM
no_index:
  directory:
    - t
    - inc
requires:
  WWW::Mechanize: 1.2
version: 0.13
