--- #YAML:1.0
name:                WWW-Translate-interNOSTRUM
version:             0.11
abstract:            Catalan < > Spanish machine translation
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    WWW::Mechanize:                1.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Enrique Nell <perl_nell@telefonica.net>
